cloud:
  aws:
    credentials:
      accessKey: AKIAWYXO7AWR4H2W2WXQ
      secretKey: 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
    s3:
      bucket: instaclonepjt-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: '265616719074915'
            scope: public_profile,email
            client-secret: e07513ac52da58a732047bf6dc755edd

